In [1]:
import sys
sys.path.append('.')

import numpy as np
from classes.RigidBody import RigidBody
from classes.Ground import Ground
from classes.RotationalJoint import RotationalJoint

In [2]:
ground = Ground()
link1 = RigidBody(m_B=2,B_I_B=5*np.eye(3))
link2 = RigidBody(m_B=2,B_I_B=5*np.eye(3))

joint1 = RotationalJoint(ground,link1)
joint2 = RotationalJoint(link1,link2)

In [3]:
joint1.qIndex = 0
joint2.qIndex = 1

ground.setup(2)

In [6]:
joint1.q = np.array(30*np.pi/180)
joint2.q = np.array(10*np.pi/180)

ground.updateKinTree()

NameError: name 'np' is not defined

In [5]:
link1.A_IB

array([[2.73205081, 2.73205081, 2.73205081],
       [2.73205081, 2.73205081, 2.73205081],
       [2.73205081, 2.73205081, 2.73205081]])

In [4]:
np.array([0.0042,0.8354,0.8354]) @ np.eye(3)
np.diag([0.0042,0.8354,0.8354])

array([[0.0042, 0.    , 0.    ],
       [0.    , 0.8354, 0.    ],
       [0.    , 0.    , 0.8354]])

In [2]:
a = np.array([1,2,3,4,5])
a[[1,2]]

array([2, 3])